#pragma once
#include <vector>
#include "flintpp.h"
#include "iostream"
#include <fstream>
#include <string>
#include <windows.h>
#include <omp.h>
#include <random>
#include <cstdlib>
#include "kernel.h"